---
abstract: 'YouTube title-fetch plugin for Bot::Cobalt'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-Plugin-YouTube
provides:
  Bot::Cobalt::Plugin::YouTube:
    file: lib/Bot/Cobalt/Plugin/YouTube.pm
    version: 0.002
requires:
  Bot::Cobalt: 0.003
  HTML::TokeParser: 3.69
  HTTP::Request: 0
  URI::Escape: 0
  perl: v5.10.1
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
