---
abstract: 'YouTube plugin for Bot::Cobalt'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-Plugin-YouTube
requires:
  Bot::Cobalt: 0
  Carp: 0
  HTML::TokeParser: 3.69
  HTTP::Request: 0
  URI::Escape: 0
  perl: v5.12.1
  strictures: 1
resources:
  repository: git://github.com/avenj/bot-cobalt-plugin-youtube.git
version: 0.003000
